name: Line
description: A simple Flutter app showing daily quotes.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/happy.json
    - assets/lottie/sad.json
    - assets/lottie/angry.json
    - assets/lottie/calm.json
    - assets/lottie/excited.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # Replace with your image path