import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:lottie/lottie.dart';
import 'dart:math';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky); // Fullscreen
  runApp(const DailyQuotesApp());
}

class DailyQuotesApp extends StatefulWidget {
  const DailyQuotesApp({super.key});

  @override
  State<DailyQuotesApp> createState() => _DailyQuotesAppState();
}

class _DailyQuotesAppState extends State<DailyQuotesApp> {
  Locale _locale = const Locale('en');

  void _changeLanguage(Locale newLocale) {
    setState(() {
      _locale = newLocale;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Line',
      locale: _locale,
      supportedLocales: const [
        Locale('en'),
        Locale('es'),
        Locale('fr'),
      ],
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      home: QuoteScreen(onLanguageChange: _changeLanguage),
    );
  }
}

class QuoteScreen extends StatefulWidget {
  final void Function(Locale) onLanguageChange;
  const QuoteScreen({super.key, required this.onLanguageChange});

  @override
  State<QuoteScreen> createState() => _QuoteScreenState();
}

class _QuoteScreenState extends State<QuoteScreen> {
  String selectedEmotion = 'happy';
  String quote = '';

  final Map<String, Map<String, List<String>>> emotionQuotes = const {
    'happy': {
      'en': [
        "Happiness is a journey, not a destination.",
        "Smile, it's free therapy.",  "Do more of what makes you happy.",
        "Be the reason someone smiles today.",
        "The purpose of our lives is to be happy.",
        "Happiness depends upon ourselves.",
        "Happiness is not something ready made. It comes from your own actions.",
        "For every minute you are angry you lose sixty seconds of happiness.",
        "Happiness is when what you think, what you say, and what you do are in harmony.",
        "Count your age by friends, not years. Count your life by smiles, not tears.",
        "The best way to cheer yourself up is to try to cheer somebody else up.",
        "Happiness is not a goal; it is a by-product.",
        "Happiness is only real when shared.",
        "Happiness is the secret to all beauty. There is no beauty without happiness.",
        "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
        "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.",
        "Happiness is a warm puppy.",
        "Happiness is not a state to arrive at, but a manner of traveling.",
        "Happiness is the best makeup.",
        "Happiness is a choice that requires effort at times.",
        "Happiness is a direction, not a place.",
        "Happiness is not something you postpone for the future; it is something you design for the present.",
        "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.",
        "Happiness is not having what you want. It is appreciating what you have.",
        "Happiness is a perfume you cannot pour on others without getting some on yourself.",
      ],
      'es': [
        "La felicidad es un viaje, no un destino.",
        "Sonríe, es una terapia gratuita.",
        "Haz más de lo que te hace feliz.",
        "Sé la razón por la que alguien sonríe hoy.",
        "El propósito de nuestras vidas es ser felices.",
        "La felicidad depende de nosotros mismos.",
        "La felicidad no es algo prefabricado. Viene de tus propias acciones.",
        "Por cada minuto que estás enojado, pierdes sesenta segundos de felicidad.",
        "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.",
        "Cuenta tu edad por amigos, no por años. Cuenta tu vida por sonrisas, no por lágrimas.",
        "La mejor manera de animarte es intentar animar a alguien más.",
        "La felicidad no es una meta; es un subproducto.",
        "La felicidad solo es real cuando se comparte.",
        "La felicidad es el secreto de toda belleza. No hay belleza sin felicidad.",
        "La felicidad es el arte de no mantener en la mente ningún recuerdo desagradable que haya pasado.",
        "La felicidad no está en la mera posesión de dinero; radica en la alegría del logro, en la emoción del esfuerzo creativo.",
        "La felicidad es un cachorro caliente.",
        "La felicidad no es un estado al que llegar, sino una forma de viajar.",
        "La felicidad es el mejor maquillaje.",
        "La felicidad es una elección que requiere esfuerzo a veces.",
        "La felicidad es una dirección, no un lugar.",
        "La felicidad no es algo que pospones para el futuro; es algo que diseñas para el presente.",
        "La felicidad es el significado y el propósito de la vida, el objetivo y fin de la existencia humana.",
        "La felicidad no es tener lo que quieres. Es apreciar lo que tienes.",
        "La felicidad es un perfume que no puedes verter sobre otros sin obtener un poco en ti mismo.",
      ],
      'fr': [
        "Le bonheur est un voyage, pas une destination.",
        "Souriez, c'est une thérapie gratuite.",
        "Faites plus de ce qui vous rend heureux.",
        "Soyez la raison pour laquelle quelqu'un sourit aujourd'hui.",
        "Le but de nos vies est d'être heureux.",
        "Le bonheur dépend de nous-mêmes.",
        "Le bonheur n'est pas quelque chose de prêt à l'emploi. Il vient de vos propres actions.",
        "Pour chaque minute que vous êtes en colère, vous perdez soixante secondes de bonheur.",
        "Le bonheur, c'est lorsque ce que vous pensez, ce que vous dites et ce que vous faites sont en harmonie.",
        "Comptez votre âge par amis, pas par années. Comptez votre vie par sourires, pas par larmes.",
        "La meilleure façon de vous remonter le moral est d'essayer de remonter le moral de quelqu'un d'autre.",
        "Le bonheur n'est pas un but; c'est un sous-produit.",
        "Le bonheur n'est réel que lorsqu'il est partagé.",
        "Le bonheur est le secret de toute beauté. Il n'y a pas de beauté sans bonheur.",
        "Le bonheur est l'art de ne jamais garder à l'esprit le souvenir de quelque chose de désagréable qui est passé.",
        "Le bonheur n'est pas dans la simple possession d'argent; il réside dans la joie de l'accomplissement, dans le frisson de l'effort créatif.",
        "Le bonheur est un chiot chaud.",
        "Le bonheur n'est pas un état auquel arriver, mais une manière de voyager.",
        "Le bonheur est le meilleur maquillage.",
        "Le bonheur est un choix qui nécessite parfois des efforts.",
        "Le bonheur est une direction, pas un lieu.",
        "Le bonheur n'est pas quelque chose que vous remettez à plus tard pour l'avenir; c'est quelque chose que vous concevez pour le présent.",
        "Le bonheur est le sens et le but de la vie, le but ultime de l'existence humaine.",
        "Le bonheur n'est pas d'avoir ce que vous voulez. C'est apprécier ce que vous avez.",
        "Le bonheur est un parfum que vous ne pouvez pas verser sur les autres sans en obtenir un peu sur vous-même.",
      ],
    },
    'sad': {
      'en': ["Tears come from the heart","Happiness is a journey, not a destination",
        "It’s hard to forget someone who gave you so much to remember.",
        "Behind every sweet smile, there is a bitter sadness that no one can ever see or feel.",
        "Tears are words the heart can’t express.",
        "You smile, but you wanna cry. You talk, but you wanna be quiet. You pretend like you’re happy, but you aren’t.",
        "Sadness is but a wall between two gardens.",
        "The word ‘happy’ would lose its meaning if it were not balanced by sadness.",
        "It’s okay to feel sad sometimes. It’s okay to cry.",
        "The pain never really goes away; you just learn to live with it.",
        "Every human walks around with a certain kind of sadness.",
        "The saddest thing about betrayal is that it never comes from your enemies.",
        "Loneliness is not being alone. It’s the feeling that no one cares.",
        "My silence is just another word for my pain.",
        "People cry not because they’re weak but because they’ve been strong for too long.",
        "You never know how strong you are until being strong is the only choice you have.",
        "Sometimes, we create our own heartbreaks through expectation.",
        "A broken heart bleeds tears.",
        "Sometimes, the person you’d take a bullet for is the one behind the trigger.",
        "The worst kind of sad is not being able to explain why.",
        "It hurts when you realize you aren’t as important to someone as you thought you were.",
        "The scars you can’t see are the hardest to heal.",
        "The soul would have no rainbow if the eyes had no tears.",
        "Sadness flies away on the wings of time.",
        "It’s sad when someone you know becomes someone you knew.",
        "There is no greater sorrow than to recall happiness in times of misery.",
        "Pain is inevitable. Suffering is optional.",
        "Some people are going to leave, but that’s not the end of your story.",
        "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.",
        "Even the darkest night will end and the sun will rise.",
        "A sad soul can kill you quicker than a germ.",
        "Better to have loved and lost than never to have loved at all.",
        "I wish I could go back to the day I met you and just walk away.",
        "The worst feeling isn’t being lonely. It’s being forgotten by someone you can’t forget.",
        "My sadness has become a part of me.",
        "Grief is just love with no place to go.",
        "The deepest people are the ones who’ve been hurt the most.",
        "Sometimes you have to know when to stop hoping.",
        "Tears are the summer showers to the soul.",
        "It’s hard to find joy when all you feel is sorrow.",
        "Behind every fake smile is a broken heart.",
        "We are all broken—that’s how the light gets in.",
        "You can wipe away the tears, but not the pain.",
        "You left and I stayed behind, broken and sad.",
        "I feel like I’m waiting for something that’s never going to happen.",
        "Sadness is an ocean. Sometimes we drown, sometimes we swim.",
        "The most painful goodbyes are the ones never said.",
        "It’s the kind of heartache you can feel in your bones.",
        "The hardest part is waking up in the morning, remembering what you were trying to forget last night.",
        "You broke me, but I still find myself hoping for you.",
        "I’m not okay, but I smile anyway.",
        "Nobody notices your sadness until it turns into anger.",
        "Sleep doesn’t help if it’s your soul that’s tired.",
        "The sad truth is the truth is sad.",
        "I’m just tired of everything, and I don’t know why.",
        "Don’t let your happiness depend on something you may lose.",
        "It’s always worse when the person you trusted the most breaks you.",
        "When you’re happy, you enjoy the music. When you’re sad, you understand the lyrics.",
        "Sometimes, you have to pretend everything is fine.",
        "All it takes is a beautiful fake smile to hide an injured soul.",
        "My heart is tired of being broken.",
        "Sadness is like a dark cloud hanging over your day.",
        "Sometimes, tears say all that words can’t.",
        "It’s sad when the person who gave you the best memories becomes a memory.",
        "I’m drowning in my thoughts, and no one can see it.",
        "The worst part of sadness is pretending to be okay.",
        "Even smiling feels like a chore.",
        "Depression is being colorblind and constantly told how colorful the world is.",
        "I’m just exhausted from trying to be okay.",
        "I’m here, but I’m not really here.",
        "My feelings? Oh, don’t worry about those. No one else does.",
        "You left me when I needed you most.",
        "I wanted to be loved, but I ended up being used.",
        "You can’t heal in the same environment that made you sick.",
        "The pain I feel is the proof I’m still alive.",
        "I thought I mattered, but I was wrong.",
        "Sadness is a quiet room.",
        "Even the strongest feelings expire when ignored.",
        "It’s not the goodbye that hurts. It’s the flashbacks that follow.",
        "I tried so hard to forget you, but the harder I tried, the more I remembered.",
        "I hate getting flashbacks from things I don’t want to remember.",
        "My chest hurts from missing you.",
        "I feel invisible, like no one even sees me.",
        "Sadness is when everything hurts, and you can’t explain why.",
        "I’m tired of trying, tired of hoping, tired of crying.",
        "Some nights I wish I could go back in time and change everything.",
        "I’m scared to get close, and I hate being alone.",
        "All I ever did was love you. All you ever did was hurt me.",
        "I’m not myself lately.",
        "Even the brightest smile can hide the darkest heart.",
        "The sad part is you still cross my mind every single day.",
        "I wish I could go back and erase you from my memory.",
        "The silence after an argument is the loudest sadness.",
        "I’m stuck in a place I don’t belong.",
        "I fake my smiles, but I can’t fake the pain.",
        "Every time I trust someone, they show me why I shouldn’t.",
        "My heart is a battlefield of pain.",
        "Sadness is a song with no melody.",
        "I wanted a fairytale, but ended up with a nightmare.",
        "I pretend I don’t care, but I care more than I should.",
        "I miss the old me.",
        "Some pain can’t be seen but is deeply felt.",
        "I gave you my heart, and you broke it without a second thought.",
        "I feel like a chapter you skipped.",
        "Being sad and alone is a dangerous combination.",
        "I’m slowly fading away, and no one notices.",
        "My soul is tired. not the brain,", "Sadness flies away on the wings of time,"],
      'es': ["Las lágrimas vienen del corazón,","Las lágrimas provienen del corazón.",
        "La felicidad es un viaje, no un destino.",
        "Es difícil olvidar a alguien que te dio tanto para recordar.",
        "Detrás de cada dulce sonrisa hay una tristeza amarga que nadie puede ver ni sentir.",
        "Las lágrimas son palabras que el corazón no puede expresar.",
        "Sonríes, pero quieres llorar. Hablas, pero quieres callar. Pretendes estar feliz, pero no lo estás.",
        "La tristeza es solo una pared entre dos jardines.",
        "La palabra ‘feliz’ perdería su significado si no estuviera equilibrada con la tristeza.",
        "Está bien sentirse triste a veces. Está bien llorar.",
        "El dolor nunca desaparece realmente; solo aprendes a vivir con él.",
        "Cada ser humano camina con un tipo de tristeza.",
        "Lo más triste de la traición es que nunca viene de tus enemigos.",
        "La soledad no es estar solo. Es sentir que a nadie le importas.",
        "Mi silencio es solo otra palabra para mi dolor.",
        "La gente llora, no porque sea débil, sino porque ha sido fuerte durante mucho tiempo.",
        "Nunca sabes lo fuerte que eres hasta que ser fuerte es la única opción que tienes.",
        "A veces, creamos nuestras propias penas por nuestras expectativas.",
        "Un corazón roto sangra lágrimas.",
        "A veces, la persona por la que recibirías una bala es quien aprieta el gatillo.",
        "El peor tipo de tristeza es no poder explicar por qué.",
        "Duele cuando te das cuenta de que no eres tan importante para alguien como pensabas.",
        "Las cicatrices que no se ven son las más difíciles de sanar.",
        "El alma no tendría arco iris si los ojos no tuvieran lágrimas.",
        "La tristeza vuela con las alas del tiempo.",
        "Es triste cuando alguien que conocías se convierte en alguien que conocías.",
        "No hay mayor pena que recordar la felicidad en tiempos de miseria.",
        "El dolor es inevitable. El sufrimiento es opcional.",
        "Algunas personas se irán, pero eso no es el final de tu historia.",
        "Los corazones pesados, como las nubes cargadas, se alivian dejando caer un poco de agua.",
        "Incluso la noche más oscura terminará y saldrá el sol.",
        "Un alma triste puede matarte más rápido que un germen.",
        "Es mejor haber amado y perdido que nunca haber amado.",
        "Ojalá pudiera volver al día que te conocí y simplemente alejarme.",
        "El peor sentimiento no es estar solo. Es ser olvidado por alguien que no puedes olvidar.",
        "Mi tristeza se ha convertido en parte de mí.",
        "El duelo es solo amor sin un lugar a dónde ir.",
        "Las personas más profundas son las que más han sido heridas.",
        "A veces hay que saber cuándo dejar de esperar.",
        "Las lágrimas son las lluvias de verano del alma.",
        "Es difícil encontrar alegría cuando todo lo que sientes es tristeza.",
        "Detrás de cada sonrisa falsa hay un corazón roto.",
        "Todos estamos rotos; así es como entra la luz.",
        "Puedes secar las lágrimas, pero no el dolor.",
        "Te fuiste y yo me quedé atrás, rota y triste.",
        "Siento que estoy esperando algo que nunca va a pasar.",
        "La tristeza es un océano. A veces nos ahogamos, a veces nadamos.",
        "Las despedidas más dolorosas son las que nunca se dijeron.",
        "Es el tipo de dolor que sientes en los huesos.",
        "La parte más difícil es despertar y recordar lo que tratabas de olvidar.",
        "Me rompiste, pero sigo esperando por ti.",
        "No estoy bien, pero sonrío de todos modos.",
        "Nadie nota tu tristeza hasta que se convierte en ira.",
        "Dormir no ayuda si es tu alma la que está cansada.",
        "La triste verdad es que la verdad es triste.",
        "Estoy cansado de todo y no sé por qué.",
        "No dejes que tu felicidad dependa de algo que puedas perder.",
        "Siempre es peor cuando te rompe alguien en quien confiabas.",
        "Cuando estás feliz, disfrutas la música. Cuando estás triste, entiendes la letra.",
        "A veces hay que fingir que todo está bien.",
        "Todo lo que se necesita es una sonrisa falsa para esconder un alma herida.",
        "Mi corazón está cansado de estar roto.",
        "La tristeza es como una nube oscura sobre tu día.",
        "A veces, las lágrimas dicen todo lo que las palabras no pueden.",
        "Es triste cuando la persona que te dio los mejores recuerdos se convierte en recuerdo.",
        "Me estoy ahogando en mis pensamientos, y nadie lo nota.",
        "La peor parte de la tristeza es fingir que estás bien.",
        "Incluso sonreír se siente como una tarea.",
        "La depresión es ser daltónico y que te digan lo colorido que es el mundo.",
        "Estoy agotado de tratar de estar bien.",
        "Estoy aquí, pero no realmente aquí.",
        "¿Mis sentimientos? Oh, no te preocupes por ellos. Nadie más lo hace.",
        "Me dejaste cuando más te necesitaba.",
        "Quería ser amado, pero terminé siendo usado.",
        "No puedes sanar en el mismo lugar que te enfermó.",
        "El dolor que siento es la prueba de que sigo vivo.",
        "Pensé que importaba, pero me equivoqué.",
        "La tristeza es una habitación silenciosa.",
        "Incluso los sentimientos más fuertes expiran si se ignoran.",
        "No duele la despedida, sino los recuerdos que vienen después.",
        "Intenté tanto olvidarte, pero cuanto más lo intentaba, más te recordaba.",
        "Odio tener recuerdos de cosas que no quiero recordar.",
        "Me duele el pecho de tanto extrañarte.",
        "Me siento invisible, como si nadie me viera.",
        "La tristeza es cuando todo duele y no puedes explicar por qué.",
        "Estoy cansado de intentar, de esperar, de llorar.",
        "Algunas noches deseo poder volver atrás y cambiarlo todo.",
        "Tengo miedo de acercarme, y odio estar solo.",
        "Todo lo que hice fue amarte. Todo lo que hiciste fue lastimarme.",
        "Últimamente no soy yo mismo.",
        "Incluso la sonrisa más brillante puede esconder el corazón más oscuro.",
        "Lo triste es que todavía pienso en ti todos los días.",
        "Ojalá pudiera borrar tu recuerdo de mi mente.",
        "El silencio después de una pelea es la tristeza más fuerte.",
        "Estoy atrapado en un lugar al que no pertenezco.",
        "Fingo mis sonrisas, pero no puedo fingir el dolor.",
        "Cada vez que confío en alguien, me muestra por qué no debería.",
        "Mi corazón es un campo de batalla de dolor.",
        "La tristeza es una canción sin melodía.",
        "Quería un cuento de hadas, pero terminé en una pesadilla.",
        "Finjo que no me importa, pero me importa más de lo que debería.",
        "Echo de menos a mi antiguo yo.",
        "Algunos dolores no se pueden ver, pero se sienten profundamente.",
        "Te di mi corazón, y lo rompiste sin pensarlo.",
        "Siento que fui un capítulo que pasaste por alto.",
        "Estar triste y solo es una combinación peligrosa.",
        "Me estoy desvaneciendo lentamente, y nadie lo nota.",
        "Mi alma está cansada.", "La tristeza vuela con las alas del tiempo,"],
      'fr': [
        "Les larmes viennent du cœur.",
        "Le bonheur est un voyage, pas une destination.",
        "Il est difficile d’oublier quelqu’un qui t’a donné tant à retenir.",
        "Derrière chaque doux sourire se cache une tristesse amère que personne ne peut voir ou ressentir.",
        "Les larmes sont des mots que le cœur ne peut pas exprimer.",
        "Tu souris, mais tu veux pleurer. Tu parles, mais tu veux te taire. Tu fais semblant d’être heureux, mais tu ne l’es pas.",
        "La tristesse n’est qu’un mur entre deux jardins.",
        "Le mot ‘heureux’ perdrait son sens s’il n’était pas équilibré par la tristesse.",
        "C’est normal d’être triste parfois. C’est normal de pleurer.",
        "La douleur ne disparaît jamais vraiment ; tu apprends simplement à vivre avec.",
        "Chaque être humain porte une forme de tristesse.",
        "Le plus triste dans la trahison, c’est qu’elle ne vient jamais de tes ennemis.",
        "La solitude, ce n’est pas être seul, c’est sentir que personne ne se soucie de toi.",
        "Mon silence est juste un autre mot pour ma douleur.",
        "Les gens pleurent, non pas parce qu’ils sont faibles, mais parce qu’ils ont été forts trop longtemps.",
        "Tu ne sais jamais à quel point tu es fort jusqu’à ce que c’est la seule option que tu as.",
        "Parfois, nous créons nos propres peines avec nos attentes.",
        "Un cœur brisé saigne des larmes.",
        "Parfois, la personne pour qui tu prendrais une balle est celle qui appuie sur la gâchette.",
        "Le pire type de tristesse, c’est de ne pas pouvoir expliquer pourquoi.",
        "Ça fait mal quand tu réalises que tu n’es pas aussi important pour quelqu’un que tu le pensais.",
        "Les cicatrices invisibles sont les plus difficiles à guérir.",
        "L’âme n’aurait pas d’arc-en-ciel si les yeux n’avaient pas de larmes.",
        "La tristesse s’envole avec les ailes du temps.",
        "C’est triste quand quelqu’un que tu connaissais devient quelqu’un que tu connaissais.",
        "Il n’y a pas de plus grande douleur que de se souvenir des jours heureux dans la misère.",
        "La douleur est inévitable. La souffrance est optionnelle.",
        "Certaines personnes partent, mais ce n’est pas la fin de ton histoire.",
        "Les cœurs lourds, comme les nuages, se soulagent en laissant tomber un peu d’eau.",
        "Même la nuit la plus sombre prendra fin et le soleil se lèvera.",
        "Une âme triste peut te tuer plus vite qu’un microbe.",
        "Il vaut mieux avoir aimé et perdu que de n’avoir jamais aimé.",
        "Si seulement je pouvais revenir au jour où je t’ai rencontré et m’éloigner.",
        "Le pire sentiment, ce n’est pas d’être seul. C’est d’être oublié par quelqu’un qu’on ne peut pas oublier.",
        "Ma tristesse est devenue une partie de moi.",
        "Le deuil n’est que de l’amour sans endroit où aller.",
        "Les personnes les plus profondes sont celles qui ont été le plus blessées.",
        "Parfois, il faut savoir quand arrêter d’attendre.",
        "Les larmes sont les pluies d’été de l’âme.",
        "Il est difficile de trouver la joie quand tout ce que tu ressens est la tristesse.",
        "Derrière chaque faux sourire se cache un cœur brisé.",
        "Nous sommes tous brisés ; c’est ainsi que la lumière entre.",
        "Tu peux essuyer les larmes, mais pas la douleur.",
        "Tu es parti et je suis resté, brisé et triste.",
        "J’ai l’impression d’attendre quelque chose qui n’arrivera jamais.",
        "La tristesse est un océan. Parfois on s’y noie, parfois on nage.",
        "Les adieux les plus douloureux sont ceux qui ne sont jamais prononcés.",
        "C’est le genre de douleur que tu ressens dans les os.",
        "La partie la plus difficile est de se réveiller et de se rappeler ce que tu essayais d’oublier.",
        "Tu m’as brisé, mais je t’attends encore.",
        "Je ne vais pas bien, mais je souris quand même.",
        "Personne ne remarque ta tristesse jusqu’à ce qu’elle devienne de la colère.",
        "Dormir n’aide pas si c’est ton âme qui est fatiguée.",
        "La triste vérité est que la vérité est triste.",
        "Je suis fatigué de tout et je ne sais pas pourquoi.",
        "Ne laisse pas ton bonheur dépendre de quelque chose que tu peux perdre.",
        "C’est toujours pire quand c’est quelqu’un de confiance qui te brise.",
        "Quand tu es heureux, tu apprécies la musique. Quand tu es triste, tu comprends les paroles.",
        "Parfois, il faut faire semblant que tout va bien.",
        "Un faux sourire peut cacher une âme blessée.",
        "Mon cœur est fatigué d’être brisé.",
        "La tristesse est comme un nuage noir au-dessus de ta journée.",
        "Parfois, les larmes disent tout ce que les mots ne peuvent pas.",
        "C’est triste quand la personne qui t’a donné les meilleurs souvenirs devient un souvenir.",
        "Je me noie dans mes pensées, et personne ne le remarque.",
        "La pire partie de la tristesse est de faire semblant que tout va bien.",
        "Même sourire devient une tâche.",
        "La dépression, c’est être daltonien et qu’on te dise à quel point le monde est coloré.",
        "Je suis épuisé d’essayer d’aller bien.",
        "Je suis là, mais pas vraiment là.",
        "Mes sentiments ? Oh, t’inquiète pas. Personne d’autre ne s’en soucie.",
        "Tu es parti quand j’avais le plus besoin de toi.",
        "Je voulais être aimé, mais j’ai été utilisé.",
        "Tu ne peux pas guérir dans l’endroit même qui t’a rendu malade.",
        "La douleur que je ressens est la preuve que je suis encore vivant.",
        "Je pensais compter, mais je me suis trompé.",
        "La tristesse est une pièce silencieuse.",
        "Même les sentiments les plus forts expirent s’ils sont ignorés.",
        "Ce n’est pas l’adieu qui fait mal, mais les souvenirs après.",
        "J’ai tellement essayé de t’oublier, mais plus j’essayais, plus je me souvenais.",
        "Je déteste avoir des souvenirs de choses que je ne veux pas me rappeler.",
        "Mon cœur me fait mal de te manquer.",
        "Je me sens invisible, comme si personne ne me voyait.",
        "La tristesse, c’est quand tout fait mal et que tu ne sais pas pourquoi.",
        "Je suis fatigué d’essayer, d’attendre, de pleurer.",
        "Parfois, je souhaite pouvoir tout recommencer.",
        "J’ai peur de m’attacher, et je déteste être seul.",
        "Tout ce que j’ai fait, c’est t’aimer. Tout ce que tu as fait, c’est me blesser.",
        "Dernièrement, je ne suis plus moi-même.",
        "Même le plus grand sourire peut cacher le cœur le plus sombre.",
        "Le plus triste, c’est que je pense encore à toi tous les jours.",
        "Si seulement je pouvais effacer ton souvenir de mon esprit.",
        "Le silence après une dispute est la tristesse la plus forte.",
        "Je suis coincé dans un endroit où je ne devrais pas être.",
        "Je fais semblant de sourire, mais je ne peux pas cacher la douleur.",
        "Chaque fois que je fais confiance à quelqu’un, il me montre pourquoi je ne devrais pas.",
        "Mon cœur est un champ de bataille de douleur.",
        "La tristesse est une chanson sans mélodie.",
        "Je voulais un conte de fées, mais j’ai eu un cauchemar.",
        "Je fais semblant de ne pas m’en soucier, mais je m’en soucie plus que je ne devrais.",
        "Mon ancien moi me manque.",
        "Certaines douleurs ne se voient pas, mais se sentent profondément.",
        "Je t’ai donné mon cœur, et tu l’as brisé sans hésiter.",
        "J’ai l’impression d’avoir été un chapitre que tu as survolé.",
        "Être triste et seul est une combinaison dangereuse.",
        "Je disparais lentement, et personne ne le remarque.",
        "Mon âme est fatiguée."
      ],    },
    'angry': {
      'en': [
        "Anger is one letter short of danger.",
        "Speak when you are angry and you will make the best speech you will ever regret.",
        "For every minute you remain angry, you give up sixty seconds of peace of mind.",
        "Anger doesn’t solve anything. It builds nothing, but it can destroy everything.",
        "Holding onto anger is like drinking poison and expecting the other person to die.",
        "Bitterness is like cancer. It eats upon the host.",
        "Anger is an acid that can do more harm to the vessel in which it is stored.",
        "Never go to bed angry. Stay up and plot your revenge.",
        "You will not be punished for your anger; you will be punished by your anger.",
        "Anger is a wind which blows out the lamp of the mind.",
        "He who angers you conquers you.",
        "Anger dwells only in the bosom of fools.",
        "A quick temper will make a fool of you soon enough.",
        "When anger rises, think of the consequences.",
        "Anger is one of the sinews of the soul.",
        "Keep cool; anger is not an argument.",
        "The greatest remedy for anger is delay.",
        "The best fighter is never angry.",
        "No man can think clearly when his fists are clenched.",
        "Anger is a valid emotion. It's only bad when it takes control and makes you do things you don't want to do.",
        "You can’t shake hands with a clenched fist.",
        "A moment of patience in a moment of anger saves you a hundred moments of regret.",
        "Don't hold to anger, hurt or pain. They steal your energy and keep you from love.",
        "Let your anger flow, but don’t let it drown you.",
        "When you let anger get the best of you, it brings out the worst in you.",
        "Speak when you’re angry and you’ll regret every word.",
        "Anger is a momentary madness, so control your passion or it will control you.",
        "People won’t have time for you if you are always angry or complaining.",
        "Anger is often more hurtful than the injury that caused it.",
        "Sometimes, getting angry is the only way to be heard.",
        "The strong man is not the good wrestler; the strong man is only the one who controls himself when he is angry.",
        "Don't let your anger make decisions for you.",
        "Even the nicest people have their limits.",
        "Anger is like fire—it burns inside you and everything around you.",
        "The worst tempers are those which are hidden behind a smile.",
        "Anger is a symptom, a response to pain, not the root cause.",
        "What starts in anger ends in shame.",
        "In anger, we speak and act without thinking.",
        "Anger is never without a reason, but seldom with a good one.",
        "Sometimes the best response to anger is silence.",
        "Anger makes you smaller, while forgiveness forces you to grow beyond what you were.",
        "One of the most courageous decisions you’ll ever make is to let go of anger.",
        "An angry man opens his mouth and shuts his eyes.",
        "Never reply when you are angry.",
        "Don’t waste your time in anger, regrets, worries, and grudges.",
        "Behind every angry face is a sad heart.",
        "Anger may be justified, but how you respond makes all the difference.",
        "An angry person lives in a storm, always waiting for lightning to strike.",
        "If you kick a stone in anger, you’ll hurt your foot.",
        "Speak less when you’re angry. You’ll regret less later.",
        "Sometimes anger is just sadness with no place to go.",
        "Don't get angry—get better.",
        "Being angry is easy. But being angry at the right person, to the right degree, at the right time—that’s hard.",
        "The world doesn’t respond well to anger, even if it’s justified.",
        "Anger is a sign that something needs to change.",
        "Anger can be useful, but only if you control it—not the other way around.",
        "Anger is heavy. Let it go and feel lighter.",
        "Anger is a habit that can be broken.",
        "Rage makes you forget who you are.",
        "The fire inside you should warm you, not burn you.",
        "Anger builds walls, love builds bridges.",
        "You don’t get ahead by getting even.",
        "Anger blinds the wise.",
        "A man in a passion rides a mad horse.",
        "Channel your anger into action, not destruction.",
        "It’s okay to be angry. It’s not okay to be cruel.",
        "Even in anger, remember who you are.",
        "The tongue is the only weapon that becomes sharper the more you use it in anger.",
        "You may be angry, but you still have a choice.",
        "Anger isn’t the answer. It’s just the loudest reaction.",
        "Anger is easy to get into, but hard to escape from.",
        "The first blow is often struck by the tongue.",
        "Being angry at someone is like letting them live rent-free in your head.",
        "Anger cannot drive out anger; only understanding can.",
        "Don’t act on anger—act with purpose.",
        "Your anger is valid, but your actions must be wise.",
        "Anger may give you power—but it's temporary and hollow.",
        "A storm of anger can uproot years of peace.",
        "Anger is the enemy of clarity.",
        "When you’re angry, breathe before you speak.",
        "Behind rage often lies a plea to be understood.",
        "Anger is a double-edged sword: it can protect or destroy.",
        "Master your anger before it masters you.",
        "Even justified anger can cause unjust harm.",
        "Don’t lose yourself in the heat of your temper.",
        "What you say in anger may be remembered forever.",
        "Time cools anger better than reason.",
        "Anger is an emotion. How you use it defines your character.",
        "True power lies in controlling your fury.",
        "Anger ignored becomes poison to your soul.",
        "People will forgive mistakes—but rarely the words said in anger.",
        "Letting go of anger is not weakness; it’s wisdom.",
        "Sometimes silence is the best expression of anger.",
        "If your anger becomes your identity, you’ve lost yourself.",
        "The angriest people are often the ones hurting the most.",
        "Not every insult deserves your rage.",
        "The more you carry anger, the heavier your journey.",
        "Even a flame of anger can start a wildfire.",
        "Anger thrives in misunderstanding.",
        "You’re not weak for walking away—you’re wise.",
        "Anger wants to scream; wisdom chooses to speak.",
        "A single angry moment can undo a thousand kind ones.",
        "Be angry, but do not sin.",
      ],
      'es': [
        "La ira está a un paso del peligro.",
        "Habla cuando estés enojado y dirás lo que lamentarás toda la vida.",
        "Por cada minuto de enojo, pierdes sesenta segundos de paz.",
        "La ira no resuelve nada. No construye, pero puede destruir todo.",
        "Aferrarse a la ira es como beber veneno y esperar que el otro muera.",
        "El resentimiento es como el cáncer. Consume al que lo siente.",
        "La ira es un ácido que daña más al recipiente que la contiene.",
        "Nunca te vayas a dormir enojado. Quédate despierto y planea tu venganza.",
        "No serás castigado por tu ira, sino por ella.",
        "La ira es un viento que apaga la lámpara de la mente.",
        "Quien te enfada, te domina.",
        "La ira habita solo en el corazón de los tontos.",
        "Un temperamento rápido pronto hace el ridículo.",
        "Cuando la ira se eleva, piensa en las consecuencias.",
        "La ira es uno de los nervios del alma.",
        "Mantén la calma; la ira no es un argumento.",
        "El mejor remedio para la ira es la espera.",
        "El mejor luchador nunca está enojado.",
        "Nadie puede pensar con claridad con los puños cerrados.",
        "La ira es válida. Es mala cuando te controla.",
        "No se puede dar la mano con el puño cerrado.",
        "Un momento de paciencia en la ira evita cien de arrepentimiento.",
        "No te aferres al enojo, al dolor o al rencor.",
        "Deja que la ira fluya, pero no te ahogue.",
        "Dejar que la ira te domine saca lo peor de ti.",
        "Habla enojado y te arrepentirás.",
        "La ira es locura momentánea; contrólala antes de que te controle.",
        "La gente no te escuchará si siempre estás enojado o quejándote.",
        "La ira duele más que la herida que la causó.",
        "A veces, enojarse es la única forma de ser escuchado.",
        "El fuerte no es quien vence, sino quien se controla en su ira.",
        "No tomes decisiones con enojo.",
        "Hasta la persona más amable tiene un límite.",
        "La ira es fuego: quema por dentro y alrededor.",
        "Los peores temperamentos se esconden tras una sonrisa.",
        "La ira es una respuesta al dolor, no su causa.",
        "Lo que empieza con ira termina con vergüenza.",
        "Con ira hablamos sin pensar.",
        "La ira nunca viene sin razón, pero rara vez con una buena.",
        "A veces, el mejor acto frente a la ira es el silencio.",
        "La ira te hace pequeño, el perdón te hace crecer.",
        "Una de las decisiones más valientes es dejar ir la ira.",
        "Un hombre enojado abre la boca y cierra los ojos.",
        "Nunca respondas enojado.",
        "No pierdas tiempo con ira, arrepentimientos o rencores.",
        "Detrás de un rostro enojado hay un corazón herido.",
        "La ira puede ser justa, pero tu reacción importa más.",
        "Una persona enojada vive en tormenta constante.",
        "Si pateas una piedra con ira, te dolerá el pie.",
        "Habla menos cuando estés enojado.",
        "A veces la ira es solo tristeza sin dirección.",
        "No te enojes, mejora.",
        "Es fácil enojarse. Difícil es hacerlo con la persona correcta y a tiempo.",
        "El mundo no responde bien a la ira, aunque sea justa.",
        "La ira indica que algo debe cambiar.",
        "La ira es útil solo si la controlas tú.",
        "La ira pesa. Déjala ir y aligérate.",
        "La ira es un hábito que se puede romper.",
        "La rabia te hace olvidar quién eres.",
        "El fuego interno debe darte calor, no quemarte.",
        "La ira levanta muros; el amor construye puentes.",
        "No avanzas vengándote.",
        "La ira ciega al sabio.",
        "Un hombre con pasión monta un caballo loco.",
        "Canaliza tu ira en acción, no en destrucción.",
        "Está bien enojarse. No está bien ser cruel.",
        "Incluso en la ira, recuerda quién eres.",
        "La lengua es un arma que se afila con la ira.",
        "Puedes estar enojado, pero aún tienes elección.",
        "La ira no es respuesta, solo la reacción más ruidosa.",
        "Fácil es entrar en la ira, difícil es salir.",
        "El primer golpe lo da la lengua.",
        "Estar enojado es permitir que alguien viva en tu mente sin pagar.",
        "La ira no vence a la ira, solo el entendimiento lo hace.",
        "No actúes con ira, actúa con propósito.",
        "Tu ira es válida, pero tus acciones deben ser sabias.",
        "La ira da poder falso.",
        "Una tormenta de ira arranca años de paz.",
        "La ira es enemiga de la claridad.",
        "Cuando estés enojado, respira antes de hablar.",
        "La rabia muchas veces es un grito por ser comprendido.",
        "La ira es espada de doble filo.",
        "Domina tu ira antes de que te domine.",
        "Incluso la ira justa puede hacer daño injusto.",
        "No te pierdas en el calor del temperamento.",
        "Lo que dices con ira puede marcar para siempre.",
        "El tiempo enfría la ira más que la razón.",
        "La ira es emoción. Tu uso de ella define tu carácter.",
        "El verdadero poder está en controlar tu furia.",
        "La ira ignorada se vuelve veneno para el alma.",
        "Se perdonan errores, pero no siempre palabras con ira.",
        "Soltar la ira no es debilidad, es sabiduría.",
        "El silencio a veces es la mejor expresión de enojo.",
        "Si tu ira se vuelve identidad, te perdiste.",
        "Los más enojados muchas veces son los más heridos.",
        "No toda ofensa merece tu rabia.",
        "Mientras más ira lleves, más pesada es tu vida.",
        "Una chispa de ira puede encender un incendio.",
        "La ira se alimenta de la incomprensión.",
        "No eres débil por alejarte; eres sabio.",
        "La ira grita; la sabiduría habla.",
        "Un solo momento de ira puede borrar mil de bondad.",
        "Enójate, pero no peques.",
      ],
      'fr': [
        "La colère est à un pas du danger.",
        "Parle quand tu es en colère et tu diras des choses que tu regretteras toujours.",
        "Chaque minute de colère te fait perdre soixante secondes de paix.",
        "La colère ne résout rien. Elle ne construit pas, mais elle peut tout détruire.",
        "S'accrocher à la colère, c'est comme boire du poison en espérant que l'autre meure.",
        "Le ressentiment est comme un cancer. Il consume celui qui le ressent.",
        "La colère est un acide qui fait plus de mal au récipient qu'à ce qu'il touche.",
        "Ne t'endors jamais fâché. Reste éveillé et planifie ta vengeance.",
        "Tu ne seras pas puni pour ta colère, mais par elle.",
        "La colère est un vent qui éteint la lampe de l'esprit.",
        "Celui qui te met en colère te domine.",
        "La colère habite seulement dans le cœur des insensés.",
        "Un tempérament rapide est souvent ridicule.",
        "Quand la colère monte, pense aux conséquences.",
        "La colère est un des nerfs de l'âme.",
        "Reste calme ; la colère n’est pas un argument.",
        "Le meilleur remède contre la colère est le temps.",
        "Le meilleur combattant n'est jamais en colère.",
        "Personne ne pense clairement avec les poings serrés.",
        "La colère est légitime. Elle devient mauvaise quand elle te contrôle.",
        "On ne peut pas tendre la main avec un poing fermé.",
        "Un moment de patience dans la colère évite cent regrets.",
        "Ne garde pas rancune ni colère en toi.",
        "Laisse la colère passer, mais ne te noie pas dedans.",
        "Se laisser emporter par la colère révèle le pire de nous-mêmes.",
        "Parler sous l'effet de la colère mène au regret.",
        "La colère est une folie temporaire ; contrôle-la avant qu’elle ne te contrôle.",
        "Les gens ne t'écouteront pas si tu cries toujours.",
        "La colère fait plus mal que la blessure elle-même.",
        "Parfois, être en colère est la seule façon d'être entendu.",
        "Le vrai fort est celui qui se maîtrise dans sa colère.",
        "Ne prends pas de décisions en étant en colère.",
        "Même la personne la plus gentille a ses limites.",
        "La colère est un feu : elle brûle de l'intérieur et à l’extérieur.",
        "Les pires colères se cachent derrière un sourire.",
        "La colère est souvent une réponse à la douleur.",
        "Ce qui commence avec la colère finit avec la honte.",
        "La colère fait parler sans réfléchir.",
        "La colère ne vient jamais sans raison, mais rarement pour une bonne.",
        "Parfois, le silence est la meilleure réponse à la colère.",
        "La colère te rend petit ; le pardon te fait grandir.",
        "L’un des actes les plus courageux est de lâcher la colère.",
        "Un homme en colère ouvre la bouche et ferme les yeux.",
        "Ne réponds jamais sous la colère.",
        "Ne gaspille pas ton temps avec la colère ou la rancune.",
        "Derrière un visage en colère se cache souvent un cœur blessé.",
        "La colère peut être juste, mais la réaction est ce qui compte.",
        "Une personne en colère vit dans une tempête constante.",
        "Si tu frappes une pierre par colère, c’est ton pied qui souffrira.",
        "Parle moins quand tu es en colère.",
        "Souvent, la colère est juste de la tristesse sans direction.",
        "Ne te fâche pas, améliore-toi.",
        "Il est facile de se mettre en colère. Difficile est de le faire à bon escient.",
        "Le monde ne répond pas bien à la colère, même justifiée.",
        "La colère montre que quelque chose doit changer.",
        "La colère n'est utile que si tu la contrôles.",
        "La colère pèse. Libère-toi pour être léger.",
        "La colère est une habitude qu'on peut briser.",
        "La rage te fait oublier qui tu es.",
        "Le feu intérieur doit réchauffer, non brûler.",
        "La colère construit des murs ; l'amour construit des ponts.",
        "La vengeance n’apporte jamais l’apaisement.",
        "La colère aveugle même les sages.",
        "Un homme emporté monte un cheval fou.",
        "Canalise ta colère vers l'action, pas la destruction.",
        "Il est normal d’être en colère. Ce n’est pas une excuse pour être cruel.",
        "Même en colère, souviens-toi de qui tu es.",
        "La langue est une arme qui se déchaîne avec la colère.",
        "Tu peux être en colère, mais tu as toujours le choix.",
        "La colère n'est pas une réponse, juste une réaction.",
        "Entrer dans la colère est facile, en sortir est difficile.",
        "Le premier coup est souvent porté par la langue.",
        "Être en colère, c’est laisser quelqu’un d’autre vivre dans ta tête gratuitement.",
        "La colère ne chasse pas la colère, seule la compréhension le fait.",
        "N’agis pas avec colère, agis avec but.",
        "Ta colère est valide, mais tes actions doivent être sages.",
        "La colère donne une illusion de pouvoir.",
        "Une tempête de colère peut anéantir des années de paix.",
        "La colère est ennemie de la clarté.",
        "Quand tu es en colère, respire avant de parler.",
        "Souvent, la rage est un cri d’incompréhension.",
        "La colère est une épée à double tranchant.",
        "Maîtrise ta colère avant qu’elle ne te maîtrise.",
        "Même la colère juste peut causer un tort injuste.",
        "Ne te perds pas dans l’intensité de la colère.",
        "Ce que tu dis sous la colère peut blesser pour toujours.",
        "Le temps apaise plus que la raison.",
        "La colère est une émotion ; ce que tu en fais te définit.",
        "Le vrai pouvoir est dans le contrôle de ta fureur.",
        "La colère ignorée empoisonne l'âme.",
        "On peut pardonner un acte, mais rarement des mots de colère.",
        "Lâcher la colère n’est pas une faiblesse, c’est de la sagesse.",
        "Le silence est parfois la meilleure expression de la colère.",
        "Si ta colère devient ton identité, tu es perdu.",
        "Les plus colériques sont souvent les plus blessés.",
        "Toute offense ne mérite pas ta rage.",
        "Plus tu portes de colère, plus ta vie est lourde.",
        "Une étincelle de colère peut provoquer un incendie.",
        "La colère s’alimente de l’incompréhension.",
        "S’éloigner n’est pas une faiblesse, c’est de la sagesse.",
        "La colère crie ; la sagesse parle.",
        "Un moment de colère peut effacer mille de bonté.",
        "Sois en colère, mais ne pèche pas.",
      ],
    },
    'calm': {
      'en': [
        "Calmness is the cradle of power.",
        "Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.",
        "Peace begins with a smile.",
        "Inhale peace, exhale stress.",
        "Stay calm, stay grounded.",
        "Let your soul catch up with your body.",
        "Serenity is not freedom from the storm, but peace amid the storm.",
        "Within you, there is a stillness and a sanctuary.",
        "Be like a duck—calm on the surface but paddling fiercely underneath.",
        "The quieter you become, the more you can hear.",
        "A calm mind brings inner strength and self-confidence.",
        "Silence is the true friend that never betrays.",
        "Peace is its own reward.",
        "Stillness is where creativity and solutions reside.",
        "Let go of what you can't control.",
        "Nothing can bring you peace but yourself.",
        "Stay calm, because peace always wins.",
        "Do not let the behavior of others destroy your inner peace.",
        "Calm seas never made a skilled sailor.",
        "Slow down and everything you are chasing will come around and catch you.",
        "Peace comes from within. Do not seek it without.",
        "Tranquility is a choice.",
        "The best fighter is never angry.",
        "Learn to be calm and you will always be happy.",
        "Inner peace begins the moment you choose not to allow another person to control your emotions.",
        "He who is of a calm and happy nature will hardly feel the pressure of age.",
        "Still waters run deep.",
        "A calm mind is a powerful mind.",
        "Keep calm and carry on.",
        "You cannot always control what goes on outside. But you can always control what goes on inside.",
        "In calmness lies true strength.",
        "Surrender to what is. Let go of what was. Have faith in what will be.",
        "Happiness is a choice. So is calmness.",
        "Mindfulness is a way to be present in calm and chaos alike.",
        "Calmness is the hallmark of spiritual strength.",
        "Choose calm over chaos.",
        "Nothing diminishes anxiety faster than action.",
        "Breathe deeply and let calmness fill you.",
        "Sometimes, the most productive thing you can do is relax.",
        "Remain calm in any situation and you’ll master yourself.",
        "Let your thoughts be like calm water.",
        "True power is calmness.",
        "Find peace in the present moment.",
        "Pause. Breathe. Proceed.",
        "Calm is a superpower.",
        "Practice patience and you’ll cultivate calm.",
        "When you own your breath, nobody can steal your peace.",
        "Peace is not the absence of conflict but the ability to cope with it.",
        "Don’t let the noise of the world disturb your inner quiet.",
        "Quiet the mind and the soul will speak.",
        "Peace is the result of retraining your mind to process life as it is.",
        "Be the calm in the storm.",
        "Even storms run out of rain.",
        "Seek calmness, not comfort.",
        "The calmer you are, the clearer you think.",
        "Stillness speaks louder than chaos.",
        "Let the world rush. You don’t have to.",
        "Be a lighthouse in someone’s storm.",
        "Respond with calm instead of reacting with chaos.",
        "Center yourself before engaging with the world.",
        "Don’t allow external events to disturb your inner peace.",
        "Anchor your soul in stillness.",
        "A calm spirit brings clarity.",
        "Serenity flows from acceptance.",
        "Even in turbulence, stay grounded.",
        "A calm demeanor diffuses tension.",
        "Slow is smooth, and smooth is fast.",
        "In every moment, choose calm.",
        "Let your peace be stronger than your storms.",
        "Peaceful mind, peaceful life.",
        "Balance brings peace.",
        "Inhale the future, exhale the past.",
        "Stay still until clarity emerges.",
        "Take time to be silent. The world will wait.",
        "The best antidote to chaos is calm.",
        "Beneath the noise, find peace.",
        "Be still and know you are enough.",
        "Let your mind rest like a quiet lake.",
        "Flow like water, calm and strong.",
        "Calmness conquers uncertainty.",
        "Return to your breath when overwhelmed.",
        "Composure is contagious.",
        "A calm soul is a light in the dark.",
        "Your vibe attracts your tribe. Choose calm.",
        "Let peace guide your steps.",
        "The most powerful statement is silence.",
        "Choose stillness over speed.",
        "A calm heart opens wide.",
        "Embrace the calm within.",
        "Calm isn’t weakness—it’s wisdom.",
        "To listen is to honor calmness.",
        "Let peace be your personal revolution.",
        "Hold stillness like a sacred flame.",
        "Ground yourself in breath.",
        "True grace lies in staying calm.",
        "Calm thoughts create a calm world.",
        "Serenity is strength dressed in gentleness.",
        "Tranquility is the soul’s natural state.",
        "Let your calm be louder than your fear.",
        "Calm is not a destination. It’s a daily practice.",
        "Every breath is a new chance for calm.",
        "Center your heart and let your thoughts follow.",
        "Seek not control, but calm alignment."
      ],

      'es' : [
        "La calma es la cuna del poder.",
        "Respira. Suelta. Y recuerda que este momento es el único que realmente tienes.",
        "La paz comienza con una sonrisa.",
        "Inhala paz, exhala estrés.",
        "Mantén la calma, mantente firme.",
        "Deja que tu alma alcance a tu cuerpo.",
        "La serenidad no es estar libre de tormentas, sino tener paz en medio de ellas.",
        "Dentro de ti hay una quietud y un santuario.",
        "Sé como un pato: tranquilo en la superficie pero remando intensamente por debajo.",
        "Cuanto más callado te vuelves, más puedes escuchar.",
        "Una mente tranquila trae fuerza interior y confianza.",
        "El silencio es el amigo verdadero que nunca traiciona.",
        "La paz es su propia recompensa.",
        "La quietud es donde residen la creatividad y las soluciones.",
        "Deja ir lo que no puedes controlar.",
        "Nada puede darte paz excepto tú mismo.",
        "Mantén la calma, la paz siempre gana.",
        "No dejes que el comportamiento de otros destruya tu paz interior.",
        "Mares en calma no hacen buenos marineros.",
        "Disminuye la velocidad y todo lo que persigues te alcanzará.",
        "La paz viene de adentro. No la busques afuera.",
        "La tranquilidad es una elección.",
        "El mejor luchador nunca está enojado.",
        "Aprende a estar calmado y siempre serás feliz.",
        "La paz interior comienza cuando decides no permitir que otra persona controle tus emociones.",
        "Quien tiene una naturaleza tranquila y feliz apenas siente el peso de la edad.",
        "Aguas tranquilas corren profundas.",
        "Una mente calmada es una mente poderosa.",
        "Mantén la calma y sigue adelante.",
        "No siempre puedes controlar lo que sucede afuera. Pero siempre puedes controlar lo que pasa dentro.",
        "En la calma está la verdadera fuerza.",
        "Ríndete a lo que es. Deja ir lo que fue. Ten fe en lo que será.",
        "La felicidad es una elección. La calma también.",
        "La atención plena es estar presente en la calma y en el caos.",
        "La calma es la señal de la fuerza espiritual.",
        "Elige la calma en lugar del caos.",
        "Nada reduce la ansiedad más rápido que la acción.",
        "Respira profundamente y deja que la calma te llene.",
        "A veces, lo más productivo que puedes hacer es relajarte.",
        "Permanece tranquilo en cualquier situación y te dominarás a ti mismo.",
        "Deja que tus pensamientos sean como agua tranquila.",
        "El verdadero poder está en la calma.",
        "Encuentra paz en el momento presente.",
        "Pausa. Respira. Continúa.",
        "La calma es un superpoder.",
        "Practica la paciencia y cultivarás la calma.",
        "Cuando controlas tu respiración, nadie puede robarte la paz.",
        "La paz no es la ausencia de conflicto, sino la capacidad de manejarlo.",
        "No dejes que el ruido del mundo perturbe tu tranquilidad.",
        "Calla la mente y el alma hablará.",
        "La paz es el resultado de entrenar tu mente para ver la vida tal como es.",
        "Sé la calma en medio de la tormenta.",
        "Incluso las tormentas se terminan.",
        "Busca la calma, no la comodidad.",
        "Cuanto más tranquilo estés, más clara será tu mente.",
        "La quietud habla más fuerte que el caos.",
        "Deja que el mundo se apresure. Tú no tienes que hacerlo.",
        "Sé un faro en la tormenta de alguien.",
        "Responde con calma en vez de reaccionar con caos.",
        "Céntrate antes de enfrentar al mundo.",
        "No permitas que los eventos externos perturben tu paz interior.",
        "Ancla tu alma en la quietud.",
        "Un espíritu calmado aporta claridad.",
        "La serenidad fluye desde la aceptación.",
        "Incluso en la turbulencia, mantente con los pies en la tierra.",
        "Una actitud tranquila disipa la tensión.",
        "Lento es suave, y suave es rápido.",
        "En cada momento, elige la calma.",
        "Deja que tu paz sea más fuerte que tus tormentas.",
        "Mente tranquila, vida tranquila.",
        "El equilibrio trae paz.",
        "Inhala el futuro, exhala el pasado.",
        "Permanece quieto hasta que llegue la claridad.",
        "Tómate un momento para el silencio. El mundo puede esperar.",
        "El mejor antídoto contra el caos es la calma.",
        "Debajo del ruido, encuentra la paz.",
        "Quédate quieto y recuerda que eres suficiente.",
        "Deja que tu mente descanse como un lago sereno.",
        "Fluye como el agua, tranquilo y fuerte.",
        "La calma vence a la incertidumbre.",
        "Vuelve a tu respiración cuando estés abrumado.",
        "La compostura es contagiosa.",
        "Un alma calmada es una luz en la oscuridad.",
        "Tu vibra atrae tu tribu. Elige la calma.",
        "Deja que la paz guíe tus pasos.",
        "El silencio es la declaración más poderosa.",
        "Elige la quietud en lugar de la velocidad.",
        "Un corazón tranquilo se abre ampliamente.",
        "Abraza la calma que hay en ti.",
        "La calma no es debilidad, es sabiduría.",
        "Escuchar es honrar la calma.",
        "Deja que la paz sea tu revolución personal.",
        "Sostén la quietud como una llama sagrada.",
        "Enraíza tu alma en la respiración.",
        "La verdadera gracia es mantenerse calmado.",
        "Pensamientos tranquilos crean un mundo tranquilo.",
        "La serenidad es fuerza envuelta en gentileza.",
        "La tranquilidad es el estado natural del alma.",
        "Que tu calma sea más fuerte que tu miedo.",
        "La calma no es un destino, es una práctica diaria.",
        "Cada respiración es una nueva oportunidad de estar tranquilo.",
        "Centra tu corazón y deja que tus pensamientos sigan.",
        "No busques el control, busca la alineación calmada."
      ],
      'fr': [
        "Le calme est le berceau du pouvoir.",
        "Respire. Relâche. Souviens-toi que ce moment est le seul qui compte.",
        "La paix commence par un sourire.",
        "Inspire la paix, expire le stress.",
        "Reste calme, reste fort.",
        "Laisse ton âme rattraper ton corps.",
        "La sérénité n’est pas l’absence de tempêtes, mais la paix en leur sein.",
        "En toi se trouve un sanctuaire de calme.",
        "Sois comme un canard : calme en surface mais pagayant en dessous.",
        "Plus tu deviens silencieux, plus tu entends.",
        "Un esprit calme apporte force intérieure et confiance.",
        "Le silence est un véritable ami qui ne trahit jamais.",
        "La paix est sa propre récompense.",
        "Le calme est la source de créativité et de solutions.",
        "Laisse aller ce que tu ne peux pas contrôler.",
        "Rien ne peut t’apporter la paix, sauf toi-même.",
        "Reste calme, la paix finit toujours par gagner.",
        "Ne laisse pas le comportement des autres détruire ta paix intérieure.",
        "Une mer calme n’a jamais fait de bon marin.",
        "Ralentis, et tout ce que tu poursuis te rattrapera.",
        "La paix vient de l’intérieur. Ne la cherche pas ailleurs.",
        "La tranquillité est un choix.",
        "Le meilleur combattant n’est jamais en colère.",
        "Apprends à rester calme, et tu seras toujours heureux.",
        "La paix intérieure commence lorsque tu choisis de ne pas laisser les autres contrôler tes émotions.",
        "Celui qui a une nature paisible ressent à peine le poids de l’âge.",
        "Les eaux calmes sont profondes.",
        "Un esprit calme est un esprit puissant.",
        "Reste calme et continue.",
        "Tu ne peux pas contrôler ce qui arrive dehors, mais tu peux contrôler ce qui se passe à l’intérieur.",
        "La vraie force réside dans le calme.",
        "Abandonne ce qui était. Aie foi en ce qui sera.",
        "Le bonheur est un choix. Le calme aussi.",
        "La pleine conscience, c’est être présent dans le calme comme dans le chaos.",
        "Le calme est un signe de force spirituelle.",
        "Choisis le calme au lieu du chaos.",
        "Rien ne réduit l’anxiété plus vite que l’action.",
        "Respire profondément et laisse le calme t’envahir.",
        "Parfois, le plus productif est de se détendre.",
        "Reste calme en toutes circonstances, et tu te maîtriseras.",
        "Laisse tes pensées flotter comme de l’eau tranquille.",
        "La vraie puissance est dans le calme.",
        "Trouve la paix dans le moment présent.",
        "Fais une pause. Respire. Continue.",
        "Le calme est un super pouvoir.",
        "Pratique la patience pour cultiver le calme.",
        "Contrôle ta respiration, personne ne pourra voler ta paix.",
        "La paix n’est pas l’absence de conflit mais la capacité à le gérer.",
        "Ne laisse pas le bruit du monde troubler ta tranquillité.",
        "Fais taire l’esprit, et l’âme parlera.",
        "La paix résulte d’un esprit entraîné à voir la vie telle qu’elle est.",
        "Sois le calme au milieu de la tempête.",
        "Même les tempêtes passent.",
        "Cherche le calme, pas le confort.",
        "Plus tu es tranquille, plus ton esprit est clair.",
        "Le silence parle plus fort que le chaos.",
        "Laisse le monde se presser. Toi, va doucement.",
        "Sois un phare dans la tempête de quelqu’un.",
        "Réponds avec calme au lieu de réagir avec chaos.",
        "Centre-toi avant d’affronter le monde.",
        "Ne permets pas aux événements extérieurs de troubler ta paix intérieure.",
        "Ancre ton âme dans la sérénité.",
        "Un esprit paisible apporte de la clarté.",
        "La sérénité découle de l’acceptation.",
        "Même dans la turbulence, reste ancré.",
        "Une attitude calme dissipe la tension.",
        "Lent, c’est fluide, fluide, c’est rapide.",
        "À chaque instant, choisis le calme.",
        "Laisse ta paix être plus forte que tes tempêtes.",
        "Esprit calme, vie paisible.",
        "L’équilibre apporte la paix.",
        "Inspire l’avenir, expire le passé.",
        "Reste immobile jusqu’à ce que la clarté vienne.",
        "Prends un instant de silence. Le monde peut attendre.",
        "Le meilleur remède au chaos est le calme.",
        "Sous le bruit, trouve la paix.",
        "Reste immobile et rappelle-toi que tu es suffisant.",
        "Laisse ton esprit reposer comme un lac tranquille.",
        "Coule comme l’eau, paisible et fort.",
        "Le calme surmonte l’incertitude.",
        "Reviens à ta respiration quand tu es débordé.",
        "Le calme est contagieux.",
        "Une âme calme éclaire l’obscurité.",
        "Ton énergie attire ta tribu. Choisis le calme.",
        "Laisse la paix guider tes pas.",
        "Le silence est l’affirmation la plus puissante.",
        "Choisis la tranquillité au lieu de la vitesse.",
        "Un cœur calme s’ouvre grand.",
        "Embrasse le calme qui est en toi.",
        "Le calme n’est pas une faiblesse, c’est de la sagesse.",
        "Écouter, c’est honorer le calme.",
        "Fais de la paix ta révolution personnelle.",
        "Protège la sérénité comme une flamme sacrée.",
        "Enracine ton âme dans la respiration.",
        "La véritable grâce, c’est rester calme.",
        "Des pensées paisibles créent un monde paisible.",
        "La sérénité est une force enveloppée de douceur.",
        "La tranquillité est l’état naturel de l’âme.",
        "Que ton calme soit plus fort que ta peur.",
        "Le calme n’est pas une destination, c’est une pratique quotidienne.",
        "Chaque souffle est une chance d’être calme.",
        "Centre ton cœur, et ton esprit suivra.",
        "Ne cherche pas le contrôle, cherche l’alignement paisible."
      ]    },
    'excited': {
      'en': ["Every moment is a fresh beginning,",  "Every moment is a fresh beginning.",
        "Get excited about your own life.",
        "Big things often have small beginnings.",
        "Excitement is the spark of progress.",
        "Life is too short to not be excited every day.",
        "Do more of what makes your heart race.",
        "Your passion is your power.",
        "Great things are coming your way.",
        "Be fearless in the pursuit of what sets your soul on fire.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Adventure is out there—go find it.",
        "Your energy introduces you before you even speak.",
        "Be the energy you want to attract.",
        "Don’t wait for the perfect moment—create it.",
        "Something exciting is always around the corner.",
        "Excitement is contagious—spread it!",
        "Your vibe attracts your tribe.",
        "Each day holds a surprise—embrace it.",
        "Wake up with excitement in your heart.",
        "Smile—something amazing is about to happen.",
        "Dream big, start small, act now.",
        "Your life is your story—make it an epic.",
        "Enthusiasm is the engine of success.",
        "Live boldly, love freely, laugh loudly.",
        "Joy is the simplest form of gratitude.",
        "The world is full of magic—go chase it.",
        "Make today ridiculously amazing.",
        "Stay curious. Stay excited.",
        "Celebrate every little win.",
        "Be excited by the possibilities.",
        "There is beauty in beginnings.",
        "Your dreams are valid.",
        "Energy flows where attention goes.",
        "Live with purpose, passion, and power.",
        "Excitement fuels achievement.",
        "Be thrilled by your own journey.",
        "Make your passion louder than your fear.",
        "Keep your eyes on the stars.",
        "You're capable of incredible things.",
        "Enjoy the ride, not just the destination.",
        "Shine with all you have.",
        "Today is a good day for greatness.",
        "Let joy rise like the sun.",
        "You're doing better than you think.",
        "Magic happens outside your comfort zone.",
        "One day or day one—you decide.",
        "Let your smile change the world.",
        "The best is yet to come.",
        "You're glowing with potential.",
        "Light up the world with your spark.",
        "Joy is not in things, it's in us.",
        "Stay wild, stay excited.",
        "New adventures await.",
        "Turn the page, start a new chapter.",
        "Happiness looks good on you.",
        "Feed your soul with good vibes.",
        "Let the good times roll.",
        "Be bold, be brave, be brilliant.",
        "Feel the excitement of possibility.",
        "Start where you are, use what you have.",
        "Life’s a celebration—dance through it.",
        "Positive energy opens new doors.",
        "Catch flights, not feelings—unless it excites you!",
        "You’re a magnet for miracles.",
        "Excitement turns thoughts into action.",
        "Let your excitement be stronger than your fear.",
        "Follow your fire.",
        "There's magic in doing what you love.",
        "Jump into joy!",
        "Take the risk or lose the chance.",
        "Say yes to new experiences.",
        "The thrill of the unknown is exciting.",
        "Start the day with a grateful heart.",
        "Be so happy that it excites others.",
        "Today is full of opportunity.",
        "New beginnings bring new excitement.",
        "Let your soul shine bright.",
        "Trust the excitement in your heart.",
        "Celebrate your uniqueness.",
        "Don’t just exist—live with excitement.",
        "Chase your dreams with wild enthusiasm.",
        "Let your heart leap for joy.",
        "Choose excitement over fear.",
        "Be proud of how far you’ve come.",
        "Make life your favorite adventure.",
        "There’s joy in the journey.",
        "Create moments that take your breath away.",
        "You are worthy of exciting things.",
        "Laugh often, dream big, love more.",
        "Your journey is just beginning.",
        "Rise and shine—it’s your time!",
        "Keep your fire burning.",
        "The best view comes after the hardest climb.",
        "Stay excited for what’s coming.",
        "You are destined for brilliance.",
        "Today is yours—make it epic.",
        "Fuel your goals with excitement.",
        "Love life and it will love you back.",
        "Be excited for no reason at all.",
        "Turn dreams into plans.",
        "Vibe high, shine bright.",
        "Every heartbeat is a chance to begin again.",
        "Find joy in the little things.",
        "Wake up and sparkle.",
        "Let your life be filled with sparkles of excitement.","Get excited about your own life,"],
      'es': ["Cada momento es un nuevo comienzo,", "Cada momento es un nuevo comienzo.",
        "Emociónate por tu propia vida.",
        "Las grandes cosas suelen tener pequeños comienzos.",
        "La emoción es la chispa del progreso.",
        "La vida es demasiado corta para no emocionarse cada día.",
        "Haz más de lo que acelera tu corazón.",
        "Tu pasión es tu poder.",
        "Grandes cosas vienen en camino.",
        "Sé valiente en la búsqueda de lo que enciende tu alma.",
        "El futuro pertenece a quienes creen en la belleza de sus sueños.",
        "La aventura está ahí fuera, ve a encontrarla.",
        "Tu energía te presenta antes que tus palabras.",
        "Sé la energía que quieres atraer.",
        "No esperes el momento perfecto, créalo.",
        "Siempre hay algo emocionante a la vuelta de la esquina.",
        "La emoción es contagiosa, ¡compártela!",
        "Tu vibra atrae a tu tribu.",
        "Cada día trae una sorpresa, abrázala.",
        "Despierta con emoción en el corazón.",
        "Sonríe, algo increíble está por suceder.",
        "Sueña en grande, empieza pequeño, actúa ya.",
        "Tu vida es tu historia, haz que sea épica.",
        "El entusiasmo es el motor del éxito.",
        "Vive con valentía, ama con libertad, ríe fuerte.",
        "La alegría es la forma más simple de gratitud.",
        "El mundo está lleno de magia, sal a buscarla.",
        "Haz que hoy sea ridículamente asombroso.",
        "Mantente curioso. Mantente emocionado.",
        "Celebra cada pequeña victoria.",
        "Emociónate por las posibilidades.",
        "Hay belleza en los comienzos.",
        "Tus sueños son válidos.",
        "La energía fluye donde va la atención.",
        "Vive con propósito, pasión y poder.",
        "La emoción impulsa el logro.",
        "Emociónate por tu propio viaje.",
        "Haz que tu pasión hable más fuerte que tu miedo.",
        "Mantén la mirada en las estrellas.",
        "Eres capaz de cosas increíbles.",
        "Disfruta del viaje, no solo del destino.",
        "Brilla con todo lo que tienes.",
        "Hoy es un buen día para la grandeza.",
        "Deja que la alegría se eleve como el sol.",
        "Lo estás haciendo mejor de lo que crees.",
        "La magia ocurre fuera de tu zona de confort.",
        "Un día o el primer día, tú decides.",
        "Deja que tu sonrisa cambie el mundo.",
        "Lo mejor está por venir.",
        "Estás brillando con potencial.",
        "Ilumina el mundo con tu chispa.",
        "La alegría no está en las cosas, está en nosotros.",
        "Sigue salvaje, sigue emocionado.",
        "Nuevas aventuras te esperan.",
        "Pasa la página, comienza un nuevo capítulo.",
        "La felicidad te queda bien.",
        "Alimenta tu alma con buenas vibras.",
        "Deja que los buenos momentos fluyan.",
        "Sé valiente, sé brillante.",
        "Siente la emoción de las posibilidades.",
        "Empieza donde estás, usa lo que tienes.",
        "La vida es una celebración, ¡baila en ella!",
        "La energía positiva abre nuevas puertas.",
        "Atrapa vuelos, no sentimientos, ¡a menos que te emocionen!",
        "Eres un imán para los milagros.",
        "La emoción convierte pensamientos en acción.",
        "Deja que tu emoción sea más fuerte que tu miedo.",
        "Sigue tu fuego.",
        "Hay magia en hacer lo que amas.",
        "¡Salta hacia la alegría!",
        "Toma el riesgo o pierde la oportunidad.",
        "Di sí a nuevas experiencias.",
        "La emoción del desconocido es emocionante.",
        "Empieza el día con un corazón agradecido.",
        "Sé tan feliz que emociones a los demás.",
        "Hoy está lleno de oportunidades.",
        "Los nuevos comienzos traen nuevas emociones.",
        "Deja que tu alma brille fuerte.",
        "Confía en la emoción de tu corazón.",
        "Celebra lo que te hace único.",
        "No solo existas, vive con emoción.",
        "Persigue tus sueños con entusiasmo salvaje.",
        "Deja que tu corazón salte de alegría.",
        "Elige emoción en lugar de miedo.",
        "Esté orgulloso de lo lejos que has llegado.",
        "Haz de la vida tu aventura favorita.",
        "Hay alegría en el viaje.",
        "Crea momentos que te dejen sin aliento.",
        "Eres digno de cosas emocionantes.",
        "Ríe mucho, sueña en grande, ama más.",
        "Tu viaje apenas comienza.",
        "¡Levántate y brilla, es tu momento!",
        "Mantén tu fuego encendido.",
        "La mejor vista viene después de la escalada más dura.",
        "Mantente emocionado por lo que viene.",
        "Estás destinado a brillar.",
        "Hoy es tuyo, hazlo épico.",
        "Alimenta tus metas con emoción.",
        "Ama la vida y la vida te amará a ti.",
        "Emociónate sin razón.",
        "Convierte sueños en planes.",
        "Vibra alto, brilla fuerte.",
        "Cada latido es una oportunidad para comenzar de nuevo.",
        "Encuentra alegría en las pequeñas cosas.",
        "Despierta y resplandece.",
        "Deja que tu vida se llene de destellos de emoción.","Emociónate por tu propia vida,"],
      'fr': ["Chaque moment est un nouveau départ,","Chaque moment est un nouveau départ.",
        "Sois enthousiaste pour ta propre vie.",
        "Les grandes choses commencent souvent petit.",
        "L'excitation est l'étincelle du progrès.",
        "La vie est trop courte pour ne pas s'enthousiasmer chaque jour.",
        "Fais plus de ce qui fait battre ton cœur.",
        "Ta passion est ta puissance.",
        "De grandes choses arrivent.",
        "Sois courageux dans la poursuite de ce qui enflamme ton âme.",
        "L'avenir appartient à ceux qui croient en la beauté de leurs rêves.",
        "L'aventure est là dehors, pars à sa rencontre.",
        "Ton énergie te précède.",
        "Sois l'énergie que tu veux attirer.",
        "N'attends pas le moment parfait, crée-le.",
        "Il y a toujours quelque chose d’excitant à découvrir.",
        "L'excitation est contagieuse, partage-la !",
        "Ta vibration attire ta tribu.",
        "Chaque jour apporte une surprise, accueille-la.",
        "Réveille-toi avec de l’excitation dans le cœur.",
        "Souris, quelque chose d’incroyable va se produire.",
        "Rêve grand, commence petit, agis maintenant.",
        "Ta vie est ton histoire, rends-la épique.",
        "L’enthousiasme est le moteur du succès.",
        "Vis avec courage, aime librement, ris fort.",
        "La joie est la forme la plus simple de gratitude.",
        "Le monde est rempli de magie, sors la découvrir.",
        "Fais de ce jour un jour extraordinairement génial.",
        "Reste curieux. Reste enthousiaste.",
        "Célèbre chaque petite victoire.",
        "Sois excité par les possibilités.",
        "Il y a de la beauté dans les commencements.",
        "Tes rêves sont valables.",
        "L'énergie va là où va l'attention.",
        "Vis avec but, passion et puissance.",
        "L'excitation pousse à l'accomplissement.",
        "Sois excité par ton propre voyage.",
        "Laisse ta passion parler plus fort que ta peur.",
        "Garde les yeux tournés vers les étoiles.",
        "Tu es capable de choses incroyables.",
        "Apprécie le voyage autant que la destination.",
        "Brille de tout ton éclat.",
        "Aujourd'hui est un bon jour pour la grandeur.",
        "Laisse la joie se lever comme le soleil.",
        "Tu fais mieux que tu ne le crois.",
        "La magie opère hors de ta zone de confort.",
        "Un jour ou le premier jour, tu choisis.",
        "Laisse ton sourire changer le monde.",
        "Le meilleur reste à venir.",
        "Tu rayonnes de potentiel.",
        "Éclaire le monde avec ton étincelle.",
        "La joie ne vient pas des choses, elle vient de nous.",
        "Reste sauvage, reste enthousiaste.",
        "De nouvelles aventures t'attendent.",
        "Tourne la page, commence un nouveau chapitre.",
        "Le bonheur te va bien.",
        "Nourris ton âme de bonnes vibrations.",
        "Laisse couler les bons moments.",
        "Sois audacieux, sois lumineux.",
        "Ressens l'excitation des possibilités.",
        "Commence là où tu es, avec ce que tu as.",
        "La vie est une fête, danse-y !",
        "L'énergie positive ouvre de nouvelles portes.",
        "Attrape des vols, pas des sentiments – sauf s’ils t’excitent !",
        "Tu es un aimant à miracles.",
        "L'excitation transforme les pensées en action.",
        "Laisse ton enthousiasme être plus fort que ta peur.",
        "Suis ta flamme.",
        "Il y a de la magie dans le fait de faire ce que tu aimes.",
        "Saute de joie !",
        "Prends le risque ou perds la chance.",
        "Dis oui à de nouvelles expériences.",
        "L'inconnu est excitant.",
        "Commence ta journée avec un cœur reconnaissant.",
        "Sois si heureux que tu enthousiasmes les autres.",
        "Aujourd'hui est rempli d'opportunités.",
        "Les nouveaux départs apportent de nouvelles émotions.",
        "Laisse ton âme briller fort.",
        "Fais confiance à l’excitation de ton cœur.",
        "Célèbre ce qui te rend unique.",
        "Ne te contente pas d’exister, vis avec passion.",
        "Pourchasse tes rêves avec enthousiasme.",
        "Laisse ton cœur bondir de joie.",
        "Choisis l’excitation plutôt que la peur.",
        "Sois fier du chemin parcouru.",
        "Fais de la vie ton aventure préférée.",
        "Il y a de la joie dans le voyage.",
        "Crée des moments qui te coupent le souffle.",
        "Tu mérites des choses excitantes.",
        "Rie beaucoup, rêve grand, aime encore plus.",
        "Ton aventure ne fait que commencer.",
        "Lève-toi et brille, c’est ton moment !",
        "Garde ta flamme vivante.",
        "La plus belle vue vient après la montée la plus dure.",
        "Reste excité pour ce qui arrive.",
        "Tu es destiné à briller.",
        "Aujourd’hui t’appartient, rends-le épique.",
        "Alimente tes buts avec excitation.",
        "Aime la vie et elle t’aimera en retour.",
        "Sois enthousiaste sans raison.",
        "Transforme tes rêves en plans.",
        "Vibre haut, brille fort.",
        "Chaque battement de cœur est une chance de recommencer.",
        "Trouve de la joie dans les petites choses.",
        "Réveille-toi et rayonne.",
        "Laisse ta vie scintiller d’excitation.", "Sois enthousiaste pour ta propre vie,"
      ],
    },
  };

  String getRandomQuote(String emotion, String lang) {
    List<String>? quotes = emotionQuotes[emotion]?[lang];
    if (quotes == null || quotes.isEmpty) {
      return "No quote available for this emotion and language.";
    }
    final index = Random().nextInt(quotes.length);
    return quotes[index];
  }

  void loadQuote() {
    String lang = Localizations.localeOf(context).languageCode;
    setState(() {
      quote = getRandomQuote(selectedEmotion, lang);
    });
  }

  String getLottieForEmotion(String emotion) {
    return 'assets/lottie/$emotion.json';
  }

  List<Color> getGradientColors(String emotion) {
    switch (emotion) {
      case 'happy':
        return [Color(0xFFFFE57F), Color(0xFFF4BD01)];
      case 'sad':
        return [Color(0xFF536976), Color(0xFF292E49)];
      case 'angry':
        return [Color(0xFFFF512F), Color(0xFFDD2476)];
      case 'calm':
        return [Color(0xFF2193b0), Color(0xFF6dd5ed)];
      case 'excited':
        return [Color(0xFFFFA17F), Color(0xFFFFE259)];
      default:
        return [Color(0xFF8E2DE2), Color(0xFF4A00E0)];
    }
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      loadQuote();
    });
  }

  void showHelpDialog() {
    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        title: const Text('Contact Info'),
        content: const Text('For support, contact:\n\nLead developer : Kishore Ganeshkumar \nEmail: kishoreganeshkumar556@gmail.com\nPhone: +91 9503053553'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final screenSize = MediaQuery.of(context).size;
    final screenWidth = screenSize.width;
    final screenHeight = screenSize.height;

    String lottiePath = getLottieForEmotion(selectedEmotion);
    List<Color> bgGradient = getGradientColors(selectedEmotion);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Line'),
        centerTitle: true,
        backgroundColor: Colors.lightBlueAccent.shade100,
        actions: [
          IconButton(
            icon: const Icon(Icons.help_outline),
            tooltip: 'Help',
            onPressed: showHelpDialog,
          ),
          PopupMenuButton<String>(
            icon: const Icon(Icons.language),
            onSelected: (String langCode) {
              widget.onLanguageChange(Locale(langCode));
              loadQuote();
            },
            itemBuilder: (context) => const [
              PopupMenuItem(value: 'en', child: Text('English')),
              PopupMenuItem(value: 'es', child: Text('Spanish')),
              PopupMenuItem(value: 'fr', child: Text('French')),
            ],
          ),
        ],
      ),
    body: Container(
    width: double.infinity,
    height: double.infinity,
    decoration: BoxDecoration(
    gradient: LinearGradient(
    colors: bgGradient,
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    ),
    ),
    child: SafeArea(
    child: SingleChildScrollView(
    child: Center(
    child: Padding(
              padding: EdgeInsets.all(screenWidth * 0.06),
              child: Column(
                children: [
                  DropdownButton<String>(
                    value: selectedEmotion,
                    items: ['happy', 'sad', 'angry', 'calm', 'excited']
                        .map((emotion) => DropdownMenuItem(
                      value: emotion,
                      child: Text(
                        emotion[0].toUpperCase() + emotion.substring(1),
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: screenWidth * 0.045,
                        ),
                      ),
                    ))
                        .toList(),
                    onChanged: (value) {
                      setState(() {
                        selectedEmotion = value!;
                        loadQuote();
                      });
                    },
                  ),
                  SizedBox(height: screenHeight * 0.03),
                  Lottie.asset(
                    lottiePath,
                    height: screenHeight * 0.25,
                    errorBuilder: (context, error, stackTrace) => const Text(
                      "Animation not found",
                      style: TextStyle(color: Colors.red, fontWeight: FontWeight.bold),
                    ),
                  ),
                  SizedBox(height: screenHeight * 0.03),
                  IconButton(
                    icon: const Icon(Icons.refresh, size: 28, color: Colors.white),
                    tooltip: 'Refresh Quote',
                    onPressed: loadQuote,
                  ),
                  SizedBox(height: screenHeight * 0.02),
                  Card(
                    elevation: 8,
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: Padding(
                      padding: EdgeInsets.all(screenWidth * 0.06),
                      child: Text(
                        quote,
                        style: TextStyle(
                          fontSize: screenWidth * 0.05,
                          fontStyle: FontStyle.italic,
                          fontWeight: FontWeight.w600,
                          color: const Color(0xFF212121),
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
     ),
    );
  }
}

